import pytest

import api_host.agents.script_generation.factory as factory_module
from api_host.agents.script_agent import ScriptAgent
from api_host.agents.script_generation import (
    LangChainScriptGenerator,
    MockScriptGenerator,
    ScriptGenerationGraph,
)
from api_host.agents.script_generation.errors import (
    ScriptGenerationConfigurationError,
    ScriptGenerationServiceError,
)
from api_host.agents.script_generation.provider import ScriptGenerationRequest
from api_host.schemas.podcast_schemas import (
    PodcastLanguage,
    PodcastScript,
    PodcastStyle,
    PodcastTargetDuration,
)
from podcraft_contracts import AiProvider, EnvVar


def test_script_agent_uses_injected_generator() -> None:
    generator = FakeScriptGenerator()
    agent = ScriptAgent(generator=generator)

    result = agent.generate_script(
        text="Source text",
        style=PodcastStyle.EDUCATIONAL,
        target_duration=PodcastTargetDuration.SHORT,
        language=PodcastLanguage.SPANISH,
    )

    assert generator.request is not None
    assert generator.request.language == PodcastLanguage.SPANISH
    assert result.title == "Injected title"


def test_mock_script_generator_generates_spanish_script() -> None:
    result = MockScriptGenerator().generate(
        ScriptGenerationRequest(
            text="FastAPI coordinates the podcast generation workflow.",
            style=PodcastStyle.CONVERSATIONAL,
            target_duration=PodcastTargetDuration.SHORT,
            language=PodcastLanguage.SPANISH,
        )
    )

    assert result.title == "Fastapi Coordinates The Podcast Generation Workflow"
    assert "Bienvenido" in result.script
    assert result.estimated_duration_minutes == 2


def test_langchain_script_generator_uses_structured_model() -> None:
    structured_model = FakeStructuredScriptModel(
        PodcastScript(
            title="Generated by LangChain",
            script="Welcome to a generated episode.",
            estimated_duration_minutes=4,
        )
    )
    generator = LangChainScriptGenerator(structured_model=structured_model)

    result = generator.generate(
        ScriptGenerationRequest(
            text="LangChain should generate the script.",
            style=PodcastStyle.EDUCATIONAL,
            target_duration=PodcastTargetDuration.MEDIUM,
            language=PodcastLanguage.ENGLISH,
        )
    )

    assert result.title == "Generated by LangChain"
    assert structured_model.input is not None
    assert structured_model.input["language"] == "English"
    assert structured_model.input["target_minutes"] == 4


def test_script_generation_graph_normalizes_and_truncates_source_text() -> None:
    generator = FakeScriptGenerator()
    graph = ScriptGenerationGraph(generator=generator, max_source_chars=28)

    result = graph.generate(
        ScriptGenerationRequest(
            text="  First   sentence with extra spacing that should be truncated.  ",
            style=PodcastStyle.EDUCATIONAL,
            target_duration=PodcastTargetDuration.SHORT,
            language=PodcastLanguage.ENGLISH,
        )
    )

    assert generator.request is not None
    assert generator.request.text == "First sentence with extra"
    assert result.title == "Injected title"


def test_script_generation_graph_retries_invalid_script() -> None:
    generator = RetryScriptGenerator()
    graph = ScriptGenerationGraph(generator=generator)

    result = graph.generate(
        ScriptGenerationRequest(
            text="Source text",
            style=PodcastStyle.EDUCATIONAL,
            target_duration=PodcastTargetDuration.SHORT,
            language=PodcastLanguage.ENGLISH,
        )
    )

    assert generator.calls == 2
    assert result.script == "Recovered script"


def test_script_generation_graph_reads_limits_from_environment(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    generator = FakeScriptGenerator()
    monkeypatch.setenv(EnvVar.SCRIPT_GRAPH_MAX_SOURCE_CHARS, "19")
    monkeypatch.setenv(EnvVar.SCRIPT_GRAPH_MAX_GENERATION_ATTEMPTS, "1")

    graph = ScriptGenerationGraph(generator=generator)
    graph.generate(
        ScriptGenerationRequest(
            text="Source text that should be shortened.",
            style=PodcastStyle.EDUCATIONAL,
            target_duration=PodcastTargetDuration.SHORT,
            language=PodcastLanguage.ENGLISH,
        )
    )

    assert generator.request is not None
    assert generator.request.text == "Source text that"


def test_script_generation_graph_rejects_invalid_env_limits(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv(EnvVar.SCRIPT_GRAPH_MAX_GENERATION_ATTEMPTS, "0")

    with pytest.raises(
        ScriptGenerationConfigurationError,
        match="SCRIPT_GRAPH_MAX_GENERATION_ATTEMPTS must be greater than zero",
    ):
        ScriptGenerationGraph(generator=FakeScriptGenerator())


def test_langchain_script_generator_requires_api_key(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)

    with pytest.raises(ScriptGenerationConfigurationError, match="OPENAI_API_KEY is required"):
        LangChainScriptGenerator().generate(
            ScriptGenerationRequest(
                text="Source text",
                style=PodcastStyle.EDUCATIONAL,
                target_duration=PodcastTargetDuration.SHORT,
                language=PodcastLanguage.ENGLISH,
            )
        )


def test_langchain_script_generator_wraps_provider_errors() -> None:
    generator = LangChainScriptGenerator(structured_model=FailingStructuredScriptModel())

    with pytest.raises(ScriptGenerationServiceError, match="OpenAI script generation failed"):
        generator.generate(
            ScriptGenerationRequest(
                text="Source text",
                style=PodcastStyle.EDUCATIONAL,
                target_duration=PodcastTargetDuration.SHORT,
                language=PodcastLanguage.ENGLISH,
            )
        )


def test_build_script_generator_selects_mock(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("SCRIPT_PROVIDER", AiProvider.MOCK)

    result = factory_module.build_script_generator()

    assert isinstance(result, MockScriptGenerator)


def test_build_script_generator_selects_openai(monkeypatch: pytest.MonkeyPatch) -> None:
    provider = object()
    monkeypatch.setenv("SCRIPT_PROVIDER", AiProvider.OPENAI)
    monkeypatch.setattr(factory_module, "LangChainScriptGenerator", lambda: provider)

    result = factory_module.build_script_generator()

    assert result is provider


def test_build_script_generator_rejects_unsupported_provider(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("SCRIPT_PROVIDER", "unknown")

    with pytest.raises(ScriptGenerationConfigurationError, match="Unsupported SCRIPT_PROVIDER"):
        factory_module.build_script_generator()


class FakeScriptGenerator:
    def __init__(self) -> None:
        self.request: ScriptGenerationRequest | None = None

    def generate(self, request: ScriptGenerationRequest) -> PodcastScript:
        self.request = request
        return PodcastScript(
            title="Injected title",
            script="Injected script",
            estimated_duration_minutes=2,
        )


class FakeStructuredScriptModel:
    def __init__(self, response: PodcastScript) -> None:
        self.response = response
        self.input: dict[str, object] | None = None

    def invoke(self, input: dict[str, object]) -> PodcastScript:
        self.input = input
        return self.response


class FailingStructuredScriptModel:
    def invoke(self, input: dict[str, object]) -> PodcastScript:
        raise RuntimeError("provider failed")


class RetryScriptGenerator:
    def __init__(self) -> None:
        self.calls = 0

    def generate(self, request: ScriptGenerationRequest) -> PodcastScript:
        self.calls += 1
        if self.calls == 1:
            return PodcastScript(title="", script="", estimated_duration_minutes=0)
        return PodcastScript(
            title="Recovered title",
            script="Recovered script",
            estimated_duration_minutes=2,
        )
